### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [w-dee/outdoor_temp#1]
In the file "bme280.cpp", there is a while-loop with `millis()` and a yield. You may remove those lines.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

To check for an error, you could do this:
```
  Wire.requestFrom((uint8_t)BME280_ADDRESS, numberOfData);
  if (Wire.available() != numberOfData) {
    return 0; // i2c (bus) error
  }
 
  for (numberOfDataRead = 0; numberOfDataRead < numberOfData; numberOfDataRead++) {
    data[numberOfDataRead] = Wire.read();
  }
```

**Comment by w-dee** [comment]
Thank you.
Fixed.
